#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vmonteco </var/spool/mail/vmonteco>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/02/11 03:36:46 by vmonteco          #+#    #+#              #
#    Updated: 2024/02/11 13:36:09 by vmonteco         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

# Variables to sort :
AR =									as
AS =									nasm
RM =									rm -f
ARFLAGS =								rc
ASFLAGS =								-g
CC =									gcc
CFLAGS =								-Wall -Werror -Wextra
LDLIBS =								-lft


# Compiling variables


# Linking variables


all: $(NAME)

$(NAME):

clean:

fclean: clean

re: fclean all
